README.md

Import changes from master into Indev (v1.8.2)

Import changes from master into Indev (v1.8.2)

---

MinecraftClient/ChatBot.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Settings.cs

Fixed mistake of not adding Parsemode.ChatBotMessages
Added INI setting for sending MC|Brand. Can now be toggled on or off.  Fixes potential issue of servers denying connection based on MC|Brand.

Mistake fixing +

---

MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Settings.cs

This should fix several bugs that occur in 1.7.10, one of which involves an  ArgumentOutOfRangeException and another with plugin channels.  It also fixes the new line issue in the default config.

Fix several bugs

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/ProtocolHandler.cs

Again, next to no changes in the protocol, so all that's needed is adding 1.11.1 to the supported version list.

Add 1.11.1 support

---

MinecraftClient/Protocol/ProtocolHandler.cs

protocol version of 1.11.2 is the same as 1.11.1 = 316
http://wiki.vg/Protocol_version_numbers

add 1.11.2 to supported protocol versions

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

0x17 is the recipe book packet.  0x18 is resource pack status.
Fixes #338

Fix ID of resource pack status in 1.12+

---

README-zh-Hans.md

Do you mind if I help translating some parts that need translation? because I see that you don't have any words translate to Chinese language, maybe some users might prefer them? Thanks.
@ORelio

Chinese Transaltion for README

---

README.md

Some person may confuse with those MCC words below.
@ORelio

abbreviation

---

MinecraftClient/Commands/Look.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftCom.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

My first working with a C language _**ever**_, with the exception of some Arduino stuff, so apologies for any sloppy code.

/look command.

---

MinecraftClient/CSharpRunner.cs
MinecraftClient/ChatBot.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

As suggested, this is the MR to fix the UUID-related changes separately.
See individual commits for references.

Fix wrong guid conversion

---

MinecraftClient/McTcpClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/PacketIncomingType.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Protocol/Inventory.cs
MinecraftClient/Protocol/InventoryType.cs
MinecraftClient/Protocol/Item.cs
MinecraftClient/Settings.cs

I have been working on Inventories started by handling the OpenWindow and WindowItems packets to save inventory data. I just wanted to commit this so others can help along the way its nowhere near done but progress. The plan is to have an array of opened inventories and when edited, edit the items in it via the id using Dictionary<Item,Slot#> 
The WindowItems packet is not  fully finished as the ReadNextNBT is causing some issues but wanted to share my contributions so others can help further / fix you can ofc comment it for now until a further fix is found

Started to implement inventory handling

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs

Yet another version bump for Minecraft bugfix release.
Chat support tested and worked.

Add 1.14.2 support

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/ProtocolHandler.cs

I really like MCC, but I don't know too much about it's code. Looking at the previous pull request from @NurdTurd which added 1.14.3 support I tried to add 1.14.4 support. I hope that's enough to make it work.
Thanks again for this awesome tool.

Add 1.14.4 support

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs

This will add the 1.15.2 protocol to the client

Added the 1.15.2 protocol

---

MinecraftClient/config/README.md

Added detailed explanation for C# scripts.
Added new better styling which is easier to read

Update and rename README.txt to README.md

---

MinecraftClient/ChatBots/AutoFishing.cs
MinecraftClient/Commands/Inventory.cs

Fix AutoFish crashs on EntityDespawn and console froze when trying to get a non-exist inventory

---

MinecraftClient/ChatBots/AutoAttack.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

What a embarrassing bug
Not sure if this fixes the issue #914

Fix AutoAttack internal tps not getting updated

---

MinecraftClient/McTcpClient.cs
MinecraftClient/Protocol/Handlers/PacketIncomingType.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Settings.cs

I was finding how to know if player got killed and I found it.
Hope this feature is useful.
related issue:
#549

Add auto respawn after player dead

---

MinecraftClient/Commands/Health.cs
MinecraftClient/Commands/Status.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

Added command to check player health and saturation

---

MinecraftClient/ChatBot.cs
MinecraftClient/ChatBots/AutoAttack.cs
MinecraftClient/ChatBots/AutoEat.cs
MinecraftClient/Commands/Health.cs
MinecraftClient/Commands/Inventory.cs
MinecraftClient/Inventory/Item.cs
MinecraftClient/Inventory/ItemTypeExtensions.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/PacketIncomingType.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Settings.cs

Added AutoEat and Fixed command Health command name not changed

---

MinecraftClient/ChatBot.cs
MinecraftClient/ChatBots/AutoEat.cs

Fixed AutoAttack stop working with AutoEat enabled and no food on hotbar

---

.idea/.gitignore
MinecraftClient/Protocol/ProtocolHandler.cs

This fixes this issue #951 randomly the Mojang session server will send back a status code of 204 with no content instead of a status code of 200. Status Code 204 is just saying that it doesnt need to change anything from last time from looking at [the documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204). It still is a success code.

Fix "failed to check session cache"

---

MinecraftClient/ChatBots/AutoAttack.cs

A lot of this code is messy and has unused variables. Additionally, there are memory leaks as dead entities are not removed from memory.
Fixes some issues related to #964

Clean AutoAttack

---

MinecraftClient/Mapping/Entity.cs
MinecraftClient/McTcpClient.cs

Adds UUID to entities and fixes some of the functions that spawn them. Removes some redundant object creation.

Add UUID to entities

---

MinecraftClient/Commands/Sneak.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs

Fix EntityAction packet ID

---

MinecraftClient/Commands/Inventory.cs
MinecraftClient/Inventory/WindowActionType.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftCom.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

Add right click and middle click function for inventory

---

MinecraftClient/Protocol/Handlers/DataTypes.cs

Fix empty NBT not getting handled correctly

---

MinecraftClient/ChatBot.cs
MinecraftClient/Commands/Inventory.cs
MinecraftClient/Mapping/Entity.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/PacketOutgoingType.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftCom.cs

**Now you can easily get a player’s nickname**
**Give yourself items with /gamemode 1**

Add Entity.Name & /inventory 0 creative <slot> <itemtype> <count>

---

MinecraftClient/ChatBot.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/WinAPI/ConsoleIcon.cs

ConsoleIcon support Windows 10 on new Console & OnLatencyUpdate Event

---

MinecraftClient/Settings.cs
MinecraftClient/config/README.md

Fixes #1046 
Replaces #1048 
Work is Nekiplay's, I just copied it into a separate pull request so it can be merged properly, since they hadn't yet.

Add %login% variable

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

#1056
(Not 100% sure can solve the issue as I couldn't test it myself)

Ignore invalid resource packs

---

MinecraftClient/ChatBot.cs
MinecraftClient/Commands/Inventory.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

1. [x]  **GetGamemode() on ChatBots**
2. [x] **Gamemode check for /inventory 0 creativegive**

add GetGamemode() on ChatBots

---

MinecraftClient/ChatBot.cs
MinecraftClient/ChatBots/AutoEat.cs
MinecraftClient/McTcpClient.cs

#1060 
Also added error handling for some ChatBot API

Fix AutoEat crash

---

MinecraftClient/ChatBot.cs
MinecraftClient/Commands/Inventory.cs
MinecraftClient/Commands/Useblock.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/PacketIncomingType.cs
MinecraftClient/Protocol/Handlers/PacketOutgoingType.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs
MinecraftClient/Protocol/IMinecraftCom.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

**Open block** _chest, furnace, crafting table_
SendPlaceBlock(new Location(x, y, z), 0);
**Place Block adjacent**
https://pastebin.com/WCs7D01m

Add OnMapData event in ChatBots & OnTitle event  & UpdateSign & OnEntityEquipment & Useblock

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs
MinecraftClient/Protocol/ProtocolHandler.cs

closes https://github.com/ORelio/Minecraft-Console-Client/issues/1090

Added 1.16(.1) support

---

MinecraftClient/config/Modules/Mail.cs

I changed some lines and added the option to change settings through mc chat.

Fix for the mail script.

---

MinecraftClient/ChatBot.cs
MinecraftClient/McClient.cs

ChatBot can register their own command for interacting with user

Add command register for ChatBot

---

MinecraftClient/ChatBot.cs
MinecraftClient/ChatBots/AutoAttack.cs
MinecraftClient/Inventory/Hand.cs
MinecraftClient/Mapping/CommandBlockFlags.cs
MinecraftClient/Mapping/CommandBlockMode.cs
MinecraftClient/McClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/EntityActionType.cs
MinecraftClient/Protocol/Handlers/PacketIncomingType.cs
MinecraftClient/Protocol/Handlers/PacketOutgoingType.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs
MinecraftClient/Protocol/IMinecraftCom.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

If you want to help me with ideas, come to the streams [YouTube](https://www.youtube.com/c/Nekiplay) or my [VK ✉](https://vk.com/neki_play)

Effects list & OnScoreboardObjective event & OnEntityEffect event & OnUpdateScore event & EntityInteract (Right Click) & Hand list

---

MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs

Update player inventory and opened container after clicking on slots

Complete inventory clicking mechanism

---

MinecraftClient/config/ChatBots/PayKassa.cs

PayKassa bot

---

MinecraftClient/ChatBot.cs
MinecraftClient/Mapping/EntityTypeExtensions.cs
MinecraftClient/McClient.cs

Fix spider not considered as hostile mob
Fix crafting result slot not being handled correctly
Added new ChatBot event OnInventoryUpdate

Fix some minor bugs

---

MinecraftClient/config/ChatBots/VkMessager.cs

VkMessager bug fix

---

MinecraftClient/Commands/Entitycmd.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs

Add Entity cmd

---

MinecraftClient/MinecraftClient.csproj

Remove duplicated item in .csproj

---

MinecraftClient/ChatBots/AutoCraft.cs

Seems like AppVeyor do not support this syntax. [MSDocs](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions)

Remove local function syntax in AutoCraft

---

MinecraftClient/Mapping/EntityPalettes/EntityPalette116.cs
MinecraftClient/Mapping/EntityType.cs
MinecraftClient/Mapping/EntityTypeExtensions.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs

- Updated the 1.16/1.16.1 protocol.
- Fixed Auto Attack (Added a new field (sneaking) to the Interact Entity event (Only 1.16 and above) and GetVarBoolean for sending a boolean in form of a byte array over the network).
- Added Entity Pallete for 1.16/1.16.1.

Updated the 1.16/1.16.1 protocol. Fixed Auto Attack. Added Entity Pallete for 1.16/1.16.1.

---

MinecraftClient/Mapping/World.cs

Add FindBlock on GetWorld

---

MinecraftClient/config/ChatBots/SugarCaneMiner.cs

Fix SugarCaneMiner

---

MinecraftClient/ChatBots/AutoCraft.cs
MinecraftClient/ChatBots/AutoDrop.cs
MinecraftClient/McClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Settings.cs

New AutoDrop ChatBot

---

MinecraftClient/Protocol/Handlers/PacketIncomingType.cs
MinecraftClient/Protocol/Handlers/PacketOutgoingType.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18PacketTypes.cs

_I remember I did implemented this during the work on AutoCraft. Don't know why the code disappeared._

Add Window Confirmation

---

MinecraftClient/ChatBot.cs
MinecraftClient/config/ChatBots/VkMessager.cs

Add UnLoadBot

---

MinecraftClient/Commands/Inventory.cs

Add help information for inventory command

---

MinecraftClient/ChatBot.cs
MinecraftClient/McClient.cs

Add player join/leave event to ChatBot API

---

MinecraftClient/ChatBot.cs
MinecraftClient/McClient.cs

New Events

---

MinecraftClient/ChatBots/AutoCraft.cs

- Fix recipe parse error
- Fix crashes on crafting failure
- More precise error messages for recipe parser

Fix AutoCraft bugs

---

MinecraftClient/Inventory/WindowActionType.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs

Example usage
```cs
RegisterChatBotCommand("drag", "drag", (string cmd, string[] args) => {
// cmd args: <target slot to use> <slots to drag on...>
var arg = args.ToList();
int slot = int.Parse(arg[0]);
arg.RemoveAt(0);
// put item to cursor
WindowAction(0, slot, WindowActionType.LeftClick);
// start dragging
WindowAction(0, -999, WindowActionType.StartDragRight);
// send slots to drag on (make sure slot is empty)
foreach (var i in arg)
{
WindowAction(0, int.Parse(i), WindowActionType.AddDragRight);
}
// end dragging
WindowAction(0, -999, WindowActionType.EndDragRight);
return "ok";
});
```
_Slots to drag on can be any empty slot, even they aren't next to each other (which you can't achieve in vanilla client :D)_

Implement inventory mouse item dragging

---

MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs

Fix 1.16 entity metadata and equipment

---

MinecraftClient/Commands/Inventory.cs
MinecraftClient/Inventory/Item.cs

/inventory add show item Damage

---

MinecraftClient/McClient.cs

Fix SetSlot (#1144)

---

MinecraftClient/ChatBots/AutoAttack.cs
MinecraftClient/McClient.cs
MinecraftClient/Settings.cs
MinecraftClient/config/README.md

- New attack mode
- Fix abnormally low attack damage _(sending Animation before InteractEntity would cause this issue)_

Improve AutoAttack

---

MinecraftClient/ChatBot.cs
MinecraftClient/Commands/Entitycmd.cs
MinecraftClient/Mapping/Entity.cs
MinecraftClient/Mapping/EntityPose.cs
MinecraftClient/Mapping/EntityTypeExtensions.cs
MinecraftClient/McClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

Add Entity.Item and OnEntityMetadata event and More

---

MinecraftClient/Mapping/EntityPalettes/EntityPalette112.cs
MinecraftClient/Mapping/EntityPalettes/EntityPalette113.cs
MinecraftClient/Mapping/EntityPalettes/EntityPalette114.cs
MinecraftClient/Mapping/EntityPalettes/EntityPalette115.cs
MinecraftClient/Mapping/EntityPalettes/EntityPalette1161.cs
MinecraftClient/Mapping/EntityType.cs
MinecraftClient/Mapping/EntityTypeExtensions.cs

Update hostile mobs list

---

MinecraftClient/Inventory/ItemPalettes/ItemPalette.cs
MinecraftClient/Inventory/ItemType.cs

Fix #1232
For handling non-vanilla item (i.e. forge item)

Fix unknown item id cause crashes

---

MinecraftClient/Protocol/Handlers/DataTypes.cs

_It should be a VarInt with no boolean in front. My bad._

Fix metadata optional blockID type

---

MinecraftClient/Commands/Entitycmd.cs
MinecraftClient/Inventory/Item.cs
MinecraftClient/Mapping/Entity.cs
MinecraftClient/McClient.cs

**Entity list**
**Item**
**Hologram**
**Player**
**NPC Citizens plugin**

/entity Made more readable

---

MinecraftClient/ChatBot.cs
MinecraftClient/Inventory/ItemMovingHelper.cs
MinecraftClient/McClient.cs
MinecraftClient/MinecraftClient.csproj

From #1208
Also found a bug (i guess) while testing new class. Player inventory isn't available after the `OnAfterGameJoined` event.

Create item moving helper class

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/PacketType18Handler.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs

Nothing got changed in 1.16.3
Entity and inventory tested work.

Update supported version to 1.16.3

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fix mistake made in upgrading 1.16.3

---

MinecraftClient/ChatBots/AutoRelog.cs

Also change all debug log to use new method
Fix #1258

Fix Auto Relog not applying delay

---

MinecraftClient/ChatBots/AutoDrop.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/lang/en.ini

Finally have some time to try out my Auto-Bots and make some improvement base on the experience.

Add new command for AutoDrop

---

MinecraftClient/McClient.cs

Fix null reference when trying to get protocol version

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fix interact entity not being correctly implemented 1.16+

---

MinecraftClient/MinecraftClient.csproj
MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/PacketType18Handler.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs

Tested it on a bunch of servers, works perfectly fine, the only protocol related changes are changes to the naming scheme

1.16.4 Update

---

MinecraftClient/McClient.cs

Attempt to fix stuck with "Logging in..."

---

MinecraftClient/config/ChatBots/AutoTree.cs

This script is made to work with Minecraft auto-tree farm machine.
Example: (player is inside the red box and placing sapling. The machine do the rest)
Related: #1358

Add AutoTree ChatBot script

---

MinecraftClient/Protocol/MicrosoftAuthentication.cs

Now it will check 2FA is enabled or not and tell user about it.
_I am looking at the 2FA login and will be implemented later._
Edit:
I have no luck making 2FA to work. I would like to merge this PR first.
If anyone know how to do 2FA without browser, please offer your help.

Impove MS authentication error feedback

---

MinecraftClient/ChatBots/AutoCraft.cs

Fix #1414
Implement the missing crafting result check.

Imporve auto-craft mechanism

---

MinecraftClient/ChatBot.cs
MinecraftClient/ILogger.cs
MinecraftClient/MCLogger.cs
MinecraftClient/McClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Settings.cs

Implement new logger

---

MinecraftClient/ChatBots/AutoDrop.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/lang/en.ini

Fix player inventory being deleted by server

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general-question.md

I hope the instruction is more clear.

Update issue template

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

I had this idea in my mind a long time ago. I think it could help some low-end device not to timeout easily under heavy load.

Dynamic sleep time

---

MinecraftClient/ChatBots/ChatLog.cs

Add lock to chatlog file

---

MinecraftClient/ChatBot.cs
MinecraftClient/McClient.cs

Add command auto-unregister mechanism

---

Docker/Dockerfile
Docker/start-latest.sh
MinecraftClient/config/README.md

**What is included in this Pull Request:**
Docker support using a Dockerfile
**Why a Dockerfile?**
For people who don't want to install all the dependencies on Linux for example but already have docker installed.
**What the Dockerfile does:**
It downloads the latest build version and runs it
To download the latest version it uses the appveyor API and [jq](https://stedolan.github.io/jq/) to parse the json in the `sh` file.
**Future improvements:**
Host the docker image publicly so one doesn't have to build it themselves e.g. on [DockerHub](https://hub.docker.com)

Feature: Dockerfile

---

MinecraftClient/ChatBot.cs
MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

New entity status packet event

---

MinecraftClient/ChatBots/AutoAttack.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

Add setting for overriding attack speed for autoattack

---

MinecraftClient/MinecraftClient.csproj.user

Document: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

Specify the CSharp version to 4 in project file

---

MinecraftClient/Resources/lang/de.ini

Had some time and tried my best to translate everything.

Add German language support

---

MinecraftClient/config/ChatBots/TreeFarmer.cs

Fix TreeFarmer bot syntax error

---

MinecraftClient/config/ChatBots/TreeFarmer.cs

Invalid direction to place the sapling

Sapling direction TreeFarmer.cs

---

MinecraftClient/Json.cs
MinecraftClient/Program.cs
MinecraftClient/Protocol/ProtocolHandler.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

I read about issue #51 and investigate the problem. It seems the simple fix is just to add an additional "\r\n" at the end of the header. I added that and updated the codes to use the current API. I can get a response with world information and see that being printed in the console. I didn't find a JSON decoder in the codes, so I haven't taken further steps. Are you able to work from there? I'm willing to help if needed.

Implement Realms support

---

MinecraftClient/config/ChatBots/DiscordWebhook.cs

Improve caching and remove unused functions

Improvements Discord Webhook

---

MinecraftClient/ChatBot.cs
MinecraftClient/ChatBots/TestBot.cs
MinecraftClient/McClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/TaskWithResult.cs

I tried my best to implement this. Unfortunately for delayed task there is no way to get the returned value or the calling thread will have to wait until the task has executed.

Implement schedule main thread task with return value

---

MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftCom.cs

Actually forgot to test this method on main thread.

Fix calling schedule task cause deadlock

---

MinecraftClient/MinecraftClient.csproj
MinecraftClient/MojangAPI.cs
MinecraftClient/Protocol/MojangAPI.cs

I wanted to improve the mail script and implement UUID support. Therefore I need the Mojang API to request those.
I thought why not invest a few more minutes and improve the experience for everyone by implementing some request types mentioned in the [wiki](https://wiki.vg/Mojang_API).
I will make a seperate pull request for the mail script later.

Integration of the Mojang API

---

MinecraftClient/Logger/FileLogLogger.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Settings.cs

Add logging of color codes

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/PacketType18Handler.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs

Update version to 1.18.1

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/ProtocolHandler.cs
MinecraftClient/Protocol/Session/SessionToken.cs

_I assumed session cache with refresh token present must be a Microsoft account._

Microsoft Sign-in: Add refresh token support

---

MinecraftClient/config/README.md

This pull request fixes some spelling, typing and grammar issues of the user manual.

Fixed some spelling and typing mistakes

---

Docker/docker-compose.yml
MinecraftClient/config/README.md

This pull request adds a docker-compose.yml for managing docker containers via docker-compose. Also the user manual has been extended to describe how to use docker-compose on this project.

Added docker-compose configuration

---

MinecraftClient/Commands/Move.cs
MinecraftClient/Resources/lang/de.ini
MinecraftClient/Resources/lang/en.ini

As a solution for #1872 I have implemented a `-f` argument, which forces the movement regardless of its potential consequences.

Add "-f" to the /move command

---

MinecraftClient/config/ChatBots/SugarCaneFarmer.cs

Inspired by #1871 I wrote a script to farm a field of sugar cane fully autonomous.
| Command                  |                                                   Usage                                                  |
|--------------------------|:--------------------------------------------------------------------------------------------------------:|
| /sugarcane [range] x\|y\|z | Search for sugar cane in the given range. <br> Sort the result after the given coordinate and start farming. |
| /sugarcane stop          | Stop the farming process.

Automatic sugar cane farming

---

MinecraftClient/Resources/lang/en.ini
MinecraftClient/Resources/lang/fr.ini

Because this is the only language that I know a bit

I translated it in french

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fix for #2110
[Tested and working](https://github.com/MCCTeam/Minecraft-Console-Client/issues/2110#issuecomment-1221057766)
Also did a formatting from the Visual Studio with `CTRL + E + D`.

Fixed a crash bellow 1.16.5 and a crash on 1.19

---

MinecraftClient/Protocol/MicrosoftAuthentication.cs

Tested on Windows, Arch and Raspbian.
Needs testing on macOS x64 and Arm64.

Fix the browser not opening on Linux.

---

MinecraftClient/config/ChatBots/DiscordWebhook.cs

Fixes [this issue](https://github.com/MCCTeam/Minecraft-Console-Client/discussions/1885#discussioncomment-3434649).

Allow newer SSL/TLS protocol versions

---

MinecraftClient/McClient.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Settings.cs

Added a `timeout=30` setting as requested in the mentioned issue.

Added an option for custom timeout as requested in #1337.

---

MinecraftClient/Commands/Chunk.cs
MinecraftClient/Commands/Move.cs
MinecraftClient/Mapping/Dimension.cs
MinecraftClient/Mapping/MaterialExtensions.cs
MinecraftClient/Mapping/Movement.cs
MinecraftClient/Mapping/World.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Resources/lang/en.ini

Usage:
``/chunk status``
``/chunk status [chunkX chunkZ|locationX locationY locationZ]`` // Mark the specified chunk
``/chunk <setloading|setloaded|delete> chunkX chunkZ`` // For debugging use
``/chunk <setloading|setloaded|delete> locationX locationY locationZ`` // For debugging use

Add "/chunk status" command. (For debugging)

---

MinecraftClient/ChatBots/AutoFishing.cs
MinecraftClient/Commands/Move.cs
MinecraftClient/Mapping/Movement.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Scripting/ChatBot.cs
MinecraftClient/Settings.cs

* Supports changing position and angle after catching fish
* Some plugins will make players less profitable (or even unprofitable) when fishing in one location for a long time, such as MCMMO
* Support automatic rod switching

Upgrade Auto Fishing

---

MinecraftClient/ChatBots/FollowPlayer.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

Added an ability to follow the player using the `/follow` command as requested in #2125
Command usage: `/follow <player name|stop> [-f]`
NOTE: The bot sometimes can be a bit slow, we need to implement a method that can cancel the current Walking task, that would speed it up.
I've added a default update timer to make the bot a bit more faster, it does not go where it doesn't need to, we need to figure out what setting is the most optimal one.
Did some basic testing, seems that it is working as intended, haven't had any issues, as far as I am asked, it's ready to go, tho I want to get some feedback/ideas to improve it.
The video (Sorry for the bad quality an update to the OBS wiped my settings): 
https://streamable.com/g2gdl4

Implemented the Follow Player chat bot.

---

MinecraftClient/Mapping/Entity.cs
MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Scripting/ChatBot.cs

Fix entity metadata handling and dimension handling in 1.19.2

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

The info for the Explosion packet on the wiki.vg was wrong, fixed the packet and the wiki.

Fixed a crash on Explosion packet

---

MinecraftClient/ChatBots/AutoRespond.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Scripting/ChatBot.cs
MinecraftClient/Settings.cs
MinecraftClient/config/sample-matches.ini

Added an option to match by colors in Auto Respond bot.

---

MinecraftClient/config/ChatBots/DiscordWebhook.cs

Now using ProxiedWebRequest and sanitizing input.

Fixed and tested Discord Webhook chat bot

---

MinecraftClient/ChatBots/ScriptScheduler.cs
MinecraftClient/config/sample-tasks.ini

Added a possibility of having a random interval in the script scheduler as requested in #1830 and an example on how to do it.
Example:
```ini
[Task]
triggerOnInterval=true
timeInterval=1-15
action=send I am triggered!
```

Script Scheduler added a random interval

---

MinecraftClient/ChatBots/Alerts.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Settings.cs

Added a log file for alerts as requested in #1179

Added a log file for Alerts Chat Bot

---

MinecraftClient/ChatBots/AutoAttack.cs
MinecraftClient/Mapping/EntityTypeExtensions.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

The AutoAttack Chat Bot now can attack passive mobs and players if enabled.
It also has a black list if someone wants to blacklist certain mobs.

Upated AutoAttack bot

---

MinecraftClient/ChatBots/Map.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

**Finally,**
Made a chat bot that can render maps.
The main purpose of this chat bot for the time being is to enable people to **solve captchas** on servers which use maps for verification.
**Current limitations:**
Since I was not able to find proper color mappings for the maps, the colors are not like in Minecraft and are weird and are looking ugly, but they do the job. I'll continue the search for the color mappings, and I'll take a look at the source code of the game too.
**Current feature set:**
- Render maps (*obviously*)
- Option to resize the rendered maps (*The default one is 128x128, quite small. The resizing cuts on quality, but can be useful*) (*Disabled by default*)
- Option to automatically render maps as they're received (*This can help with servers where the time to solve …

Map Chat Bot

---

MinecraftClient/Commands/Bed.cs
MinecraftClient/Commands/Dig.cs
MinecraftClient/Commands/Look.cs
MinecraftClient/Commands/Move.cs
MinecraftClient/Commands/Useblock.cs
MinecraftClient/Mapping/Location.cs

``public static Location Parse(string x, string y, string z);``
``public static bool TryParse(string x, string y, string z, out Location? location);``
with ``~`` support:
``public static Location Parse(Location current, string x, string y, string z);``
``public static bool TryParse(Location current, string x, string y, string z, out Location? location);``
---
``FormatException`` will be thrown when ``Parse`` fails.

Implement Location.Parse

---

README-zh-Hans.md

As the README has undergone major changes, the old translation of the README is now outdated. This PR contains works for bring the zh-Hans translation up to date.

docs(README-zh-Hans): Translation work for the new version of README

---

MinecraftClient/ChatBots/Alerts.cs
MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Resources/lang/zh-CHS.ini
MinecraftClient/Scripting/ChatBot.cs
MinecraftClient/Settings.cs

Alerts ChatBot: Support trigger on weather change

---

README-zh-Hans.md

This is a fix of a mistake that I made in #2224

docs(README-zh-Hans): Fix Typo

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fix BadPacket

---

MinecraftClient/Commands/BlockInfo.cs
MinecraftClient/Resources/lang/en.ini

Added `/blockinfo <x> <y> <z> [-s]`

Implemented block reporting as requested in #1762

---

MinecraftClient/ChatBots/Farmer.cs
MinecraftClient/Resources/lang/en.ini

Updated the command description to make it more readable and translated 2 remaining strings.

Updated Farmer bot and Enchant command translations

---

MinecraftClient/Commands/Bed.cs
MinecraftClient/Commands/BlockInfo.cs
MinecraftClient/Commands/Enchant.cs
MinecraftClient/Inventory/EnchantmentData.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Scripting/ChatBot.cs

Added safeguards for levels to the `/enchant` command,
Added Terrain Handling Requirement warning to the `/bed` and `/blockinfo` commands.
Added an additional cleaner method for Enchantments to the `ChatBot` class.

Improvements to the Bed, Blockinfo and Enchant commands.

---

MinecraftClient/Commands/BlockInfo.cs

Fixed BlockInfo overwrite.

---

MinecraftClient/ChatBots/Farmer.cs
MinecraftClient/Mapping/World.cs

Tested using the Farm bot, on the same configuration of farmland, both ran for the same period of time from the same start position.
Tweaked the amount of bone mealing in the Farmer Bot.

Switched to a faster implementation of FindBlock proposed by Daenges

---

MinecraftClient/ChatBots/DiscordBridge.cs
MinecraftClient/McClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

Implemented a chat bot bridge between the MCC and Discord.
People can send messages and commands from Discord and receive messages from the MCC.
There is also a nice way to handle Teleport requests with buttons:
TODO:
- Translate
- Look into a feasibility of implementing caching
- Add custom formatting/styling settings

Implemented a Discord Bridge Chat Bot

---

MinecraftClient/ChatBots/DiscordBridge.cs
MinecraftClient/Resources/lang/en.ini

The command: `dscbridge direction <both|mc|discord>`

Added a command for switching a direction of the Discord Bridge.

---

MinecraftClient/Protocol/ProxiedWebRequest.cs

- Support chunked transfer
- Refactor the code

ProxiedWebRequest: Support http/1.1

---

MinecraftClient/Mapping/Entity.cs

Fixed number value type during calculation of entity yaw & pitch

Fixed entity yaw and pitch

---

Docker/start-latest.sh

The permissions were being set for the wrong file

Fix docker permissions

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fixed crashing on 1.9/10/11, SpawnPainting packet was missing

---

docs/README.md

Updated Docs README.md to have 1.19.4 listed as the latest supported version

[skip ci] Updated Docs README.md to have 1.19.4 listed

---

MinecraftClient/ChatBots/Farmer.cs
MinecraftClient/Commands/ExecIf.cs
MinecraftClient/Scripting/ChatBot.cs

- Updated Farm bot to work on 1.19.3/4
- Added binding to `Random` in the `/execif` command
- Added methods for accessing App Vars in ChatBot API

Updated Farm bot to work on 1.19.3/4

---

MinecraftClient/Inventory/Item.cs

Now item lores will be displayed in the list of items in the inventory

Added item lore/description to display name in the inventory

---

MinecraftClient/Commands/Sneak.cs
MinecraftClient/Mapping/BlockExtension.cs
MinecraftClient/Mapping/MaterialExtensions.cs
MinecraftClient/Mapping/Movement.cs
MinecraftClient/McClient.cs

Added slab handling and walking under slabs, this closes: #300
Currently supported: 1.13 - 1.19.4 (Tested on 1.19.4, should work on older versions)
Note: Trapdoors are not yet supported, but now can easily be supported with this code, it's only a matter of making a palette of trapdoor states for all versions.
I will do trapdoor support as a separate pr, after this one gets tested by the player base.
Video demonstration:
https://streamable.com/vuo519

Slab handling

---

docs/guide/README.md
docs/guide/chat-bots.md
docs/guide/configuration.md
docs/guide/installation.md
docs/guide/usage.md

- Replaced net6.0 with net7.0 in the client path when compiling from the source code
- Added notes for Auto Respond limitations and fixed a wrong default value for Match Colors
- Changed the not supported versions for Entity Handling
- Addressed limitations of Terrain Handling and Physics
- Updated the image for Discord bot intents (one of the intents needed was marked as not selected, while it's needed, a lot of people have followed the image and then have asked for help with the Discord Bridge chat bot).
- Added a C# tutorials reference in the `Building from the source code` section
- Telegram Chat bot
- Items Collector bot
If you spot that I've missed something, or got it wrong, please tell me.
Thanks.

Updated documentation to reflect the newest changes

---

MinecraftClient/ChatBots/WebSocketBot.cs
MinecraftClient/Json.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/ConfigComments/ConfigComments.Designer.cs
MinecraftClient/Resources/ConfigComments/ConfigComments.resx
MinecraftClient/Resources/Translations/Translations.Designer.cs
MinecraftClient/Resources/Translations/Translations.resx
MinecraftClient/Scripting/ChatBot.cs
MinecraftClient/Settings.cs

Re-adding #2126 
Now using custom made WebSocket server, no longer using WebsocketSharp library.
Currently doing more testing, I will merge once I make sure it's fully stable.
**Description from the previous PR**
> Added a Web Socket bot that enables remote control and sends all events from ChatBot API over the network.
> 
> The motivation for this Chat Bot:
> 
>    - Enables people who know other languages and do not want to learn C# to make Chat Bots in a language of their choice
>    - Enables people to make nice UIs for controlling their MCC instances
> 
>  Current state of the Chat Bot:
> 
>     - All events from the ChatBot API are being sent
>     - Has authentication
>     - Can support multiple connections at the same time
>     - Can receive and execute MCC commands
>  
> …

Web Socket Chat Bot

---

docs/guide/WebSocketChatBot.md
docs/guide/chat-bots.md
docs/guide/usage.md

Added:
- Web socket chat bot
- `nameitem` command with examples

Updated the Documentation

---

docs/guide/websocket/Events.md
docs/guide/websocket/README.md

Trying to fix vite from crashing again

---

docs/README.md

Added 1.20 as the latest version

Updated the front page of documentation for 1.20

---

docs/.vuepress/config.ts
docs/package.json
docs/yarn.lock

Now we can use MermaidJS to plot graphs in the documentation.

Added MermaidJS graphs support to the Vuepress

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/ProtocolHandler.cs

It's the same as 1.20, no changes.

Implemented 1.20.1

---

docs/README.md

Added 1.20.1 to the documentation on the front page

[skip ci] Added 1.20.1 to the documentation

---

MinecraftClient/ChatBots/Script.cs
MinecraftClient/Resources/Translations/Translations.Designer.cs
MinecraftClient/Resources/Translations/Translations.resx
docs/guide/usage.md

Also added documentation examples and fixed an example for the `/setrnd` command

Added a random interval option to the wait command.

---

docs/guide/usage.md

ShiftClick Description was Wrong so Just Fixed it.

Inventory Click Usage Description Fix

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fixed bad code and the bug

---

MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Message/ChatParser.cs

Fixed a crash:
- with NBT parsing < 1.20.2
- with NBT Chat parsing "extra" section when you enter a wrong command

Fixes for 1.20.3

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fixed a crash with Reconfiguration... screen

Fixed a crash with Reconfiguration... screen

---

MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Message/ChatParser.cs

Fixed a crash on chat parsing. + Returned the commended try catch block.

Fixed a crash on chat parsing. + Returned the commended try catch block

---

docs/README.md

Updated the last supported version on the Documentation website front page

Documentation update (Latest Version)

---

MinecraftClient/Commands/Connect.cs
MinecraftClient/ConsoleIO.cs
MinecraftClient/McClient.cs
MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/MicrosoftAuthentication.cs
MinecraftClient/Protocol/ProfileKey/KeysCache.cs
MinecraftClient/Protocol/ProtocolHandler.cs
MinecraftClient/Protocol/Session/SessionCache.cs
MinecraftClient/Protocol/Session/SessionToken.cs
MinecraftClient/Scripting/CSharpRunner.cs
MinecraftClient/Settings.cs

fixed typo in word heAlper lol
