MinecraftClient/ChatBots/Auto Respond.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Settings.cs

This bot allows users to add a bot that can detect and respond to
certain text.
The bot can be enabled/disabled via the ini file. (disabled by default)
The bot uses 2 files to let the user set what to pickup and what to
respond.
Not sure about the changes made to some of the syntax, my environment made that changed and I haven't removed them. I've look at them and doesn't look like it would break anything.
Let me know if there is anything you're not happy about or want me to change and Ill edit it.
Kind Regards,
Bancey

Auto Respond Bot

---

MinecraftClient/ConsoleIO.cs
MinecraftClient/Protocol/ProtocolHandler.cs

This fixes [the issue that JarJpg was having](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1263927-win-mac-linux-minecraft-console-client-1-8-3?comment=1409) with logging in due to their password containing "Ð".
The main fix is the change to ProtocolHandler's jsonEncode method.  Previously,
it used ['char.IsLetterOrDigit'](https://msdn.microsoft.com/en-us/library/cay4xx2f(v=vs.110).aspx) to see if it needed to be escaped, but "Ð" is a
letter and still needs to be escaped.  The fix is to simply check if it's in
the right range.
Previously, the password `TestÐ123` would be sent as `TestÐ123`, which Mojang's servers would reject.  Now, it is sent as `Test\u00D0123`, which is the correct thing.  (Tested with an alt account).  
There's also some changes to those …

Fixed issues with passwords containing unicode special characters, such as "Ð".

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

[`MC|Brand`](http://wiki.vg/Plugin_channel#MC.7CBrand) is sent by the vanilla client on joining the game to state the version (which is usually "vanilla").  I don't know of any servers that use it, but it *is* used in some minecraft crash reports, so it probably should be sent.  The version info "Minecraft Console Client v1.8.2" is used here.

Send MC|Brand information upon joining the game

---

MinecraftClient/McTcpClient.cs
MinecraftClient/Settings.cs

Added 'loginonlyproxy' option with true / false boolean options.
on 'true' only the minecraft login is redirected to the proxy.
Otherwise both the login and the server connection are routed though the
chosen proxy.
This was mentioned by me on Minecraftforums so I eventually pulled it off myself.  Not sure if it works 100% properly BUT it does work on my test box.  True works and false does nothing new.
Provides a semi-workaround to issues #89 and #80 on ORelio/Indev

Proxy work-around / Fix.

---

MinecraftClient/McTcpClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/Forge/FMLHandshakeClientState.cs
MinecraftClient/Protocol/Handlers/Forge/FMLHandshakeDiscriminator.cs
MinecraftClient/Protocol/Handlers/Forge/ForgeInfo.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftCom.cs
MinecraftClient/Protocol/ProtocolHandler.cs

Fixes #88 and fixes #9 (although I can't seem to view #9 right now).
Connection to most modded servers running forge 1.8 and forge 1.7.10 should now be possible!
Tested with a few simple servers (a 1.8 server running rpcraft and a 1.7.10 cauldron server running a few random mods I had when I was troubleshooting a [WDL](https://github.com/pokechu22/WorldDownloader) issue).  Also tested with a [Feed The Beast infinity](http://www.feed-the-beast.com/projects/ftb-infinity/files/2260565) server, and it works, so it probably should work with most sets of mods.
The one issue is that mod i18n isn't complete, so you get things like this: 
```
>/givesample
[gendustry.givesample.usage]
```
But that doesn't seem too important or fixable at this time.
-----
Here's a bunch of technical details and how …

Add forge (1.8 and 1.7.10) support

---

MinecraftClient/ChatBot.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/Settings.cs

Because bots can send several messages quickly, this adds an option to slow down the rate at which messages are produced (to avoid issues with antispam plugins).  This should help solve part of the troubles @mobdon was having in #105.
Right now the default time is 2 seconds per message.  However, messages are sent imediately if the bot doesn't need to delay (so if it's a bot that only outputs one or two messages, those will still happen imediately).  Also, note that it's limited per-bot right now.
I also added an optional parameter to the SendText method so that bots can avoid this behavior if they need to.  In some cases, they'll want to send multiple messages.

Add an option to add a delay between bot messages

---

MinecraftClient/Protocol/Handlers/ChatParser.cs
MinecraftClient/Settings.cs

I ocasionally see untranslated messages; this should resolve all of them.
The changes to Settings.cs, the core changes, just update the index file used and the normal hash.  The changes in ChatParser.cs primarilly fix the name: 1.7.4 used 'lang/en-GB.lang' but 1.7.10 and 1.8 use 'minecraft/lang/en-GB.lang' and 'realms/lang/en-GB.lang' (and realms comes first), meaning that the wrong language file is selected.  The name is updated to make sure the right file is used.  I also corrected the indentation in that block.

Update to 1.8's language files.

---

MinecraftClient/ChatBot.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

This pull request adds some methods so that ChatBots can communicate with the server using [Plugin Channels](http://wiki.vg/Plugin_channel).  It also adds a method that is called when the client has logged in as a convenient time to register the channels.

Give bots access to plugin channels

---

MinecraftClient/McTcpClient.cs

For loop was iterating on a collection that was changed when bot[i].Update() resulted in a bot unloading, leading to index going out of range. Changed the loop collection to be immutable.

Fixed IndexOutOfRangeException when bot is unloaded on update

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

This implements the new chunk format used by 1.9, allowing terrain and movement to also be there.
However, I should note: it's really slow for some reason.  I'm not entirely sure what makes it so slow, but logging in takes about 30 seconds on my computer (during which no keep alives are received...).  It may need some revision to solve this slowness, though there is no obvious performance bottleneck.
Changes:
* Implement the teleport confirm packet, needed to allow moving in 1.9
* Store the current dimension, needed to determine whether skylight is sent
* Handle the clientbound respawn packet, because that's used when dimensions change (eg `/world`).
* Most importantly, deserialize the new [SMP map format](http://wiki.vg/SMP_Map_Format).

Implement terrain and movement for 1.9

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fixes #165.  Reduced debug info was added in 1.8, and isn't found in 1.7.  Since it isn't there in 1.7, the client would crash when it attempts to read it on the join game packet.

Stop attempting to read the reduced debug info value in 1.7

---

MinecraftClient/Settings.cs

Closed previous pull request because it needed to be cleaned up. Login and ServerIP will be checked against alias files when they are loaded.

Extend aliases for use in MinecraftClient.ini file

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/ProtocolHandler.cs

1.11 made no protocol changes that should affect this project ([here's the pre-release protocol page](http://wiki.vg/index.php?title=Pre-release_protocol&oldid=8249)).
Well, there is actually one change that _may_ affect it - the [Title packet](http://wiki.vg/index.php?title=Pre-release_protocol&oldid=8249#Title) now supports writing to the action bar just as the chat message packet does.  I didn't implement that, since the title packet is somewhat complicated, but it shouldn't cause any issues (I'm 99% certain that the chat message variant is still the primary variant used in-game, but I haven't fully checked).

Add 1.11 support

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs
README.md

This adds support for Minecraft 1.12's protocol, and also abstracts out outgoing packet IDs.
I include packet IDs for some 1.12 snapshots, even though snapshot versions aren't supported, because I already had written the code (though in a far more messy variant) for my [MC-106551](https://bugs.mojang.com/browse/MC-106551 '[MC-106551] Concurrency Issue in ThreadedAnvilChunkStorage / crash when using "/save-all flush"') test script; while they won't be used right now, they may be useful if snapshots are ever formally supported in the future.
I also did some minor cleanup of the README.

Update to 1.12

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs

Already had this set up for testing [MC-106551](https://bugs.mojang.com/browse/MC-106551 '[MC-106551] Concurrency Issue in ThreadedAnvilChunkStorage / crash when using "/save-all flush"').  A few packet IDs changed in the first snapshot, but that's it.

Implement 1.12.1 protocol

---

MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/ZlibUtils.cs

This PR does two things:
* Fixes packet compression when MCC is encoding packets.  Broken packet compression was what was causing MCC to connect to forge servers - a large outbound packet was being sent (the mod list), and that failed to compress correctly.  (I'm not entirely sure why I never had any problems with this before during the first set of forge tests, not to mention that this hasn't ever caused problems elsewhere)
There were 3 problems:
1. The compression threshold was compared with `>` when it should have been `>=`.  This didn't cause major problems since it's a rare case.
2. The compressed packet length was being used when the uncompressed length should have been used.  This broke things severely, but not as much as the next problem:
3. Only 2 or so bytes of compressed data …

Fix packet compression (+ 1 more)

---

MinecraftClient/Program.cs

Unicode characters are becoming quite common within minecraft servers (especially the large ones) nowadays. As of now MCC creates a System beep every single time one of these characters are processed by ConsoleIO. 
I'm no expert in C#, so I'm unsure if ANSI is required for anything, but I've been perfectly fine with UTF-8 so far.
(I'm still not very familiar with github so apologies if theres a duplicate of this request)

Switch console window encoding to Unicode

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/ProtocolHandler.cs

While there are protocol changes to the keep alive packet, the way MCC implements it (sending the same bytes to the server) should mean that the changes do not affect us.

Add support for 1.12.2

---

MinecraftClient/Protocol/ProtocolHandler.cs

Increase the time of the fast srvrecord setting from 5 to 10 seconds. As of now the method gets timed out before actually completing/attempting the Protocol18 DoPing causing auto to fail on most servers.

GetPing AutoTimeout timeout delay change.

---

.gitignore
MinecraftClient/Program.cs
MinecraftClient/Protocol/ChatParser.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs
MinecraftClient/Settings.cs

This MR adds a general 1.13 support. Using this version doesn't crash the client, but in particular for `terrainandmovements=true` there might be some major outstanding work.
See the relevant comment here:
https://github.com/ORelio/Minecraft-Console-Client/issues/525#issuecomment-421668400
Just FYI:
I replaced some methods like this
```c#
byte[] message_val = Encoding.UTF8.GetBytes(message);
byte[] message_len = getVarInt(message_val.Length);
byte[] data = concatBytes(message_len, message_val);
```
with a simpler
```
byte[] data = getString(message);
```
if I'm not mistaken should do the same.

525: general 1.13 support (v393 protocol)

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/ProtocolHandler.cs

It seems like there is no big changes in protocol 480 (1.14.1).
Chat support tested and worked just fine.

Add 1.14.1 support

---

MinecraftClient/ChatBot.cs
MinecraftClient/Settings.cs

Related to https://github.com/ORelio/Minecraft-Console-Client/issues/729
This MR allow to use GetServerPort/GetServerHost/GetUsername/GetUserUUID in MCC scripts
Note I left out  `GetSessionID` since I feel this should not be exposed to a MCC script

#729: allow to use GetServerPort/GetServerHost/GetUsername/GetUserUUID in MCC scripts

---

MinecraftClient/ChatBot.cs
MinecraftClient/ChatBots/AutoRelog.cs
MinecraftClient/ChatBots/AutoRespond.cs
MinecraftClient/ChatBots/Script.cs
MinecraftClient/ChatBots/ScriptScheduler.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/Settings.cs

This MR mainly fixes https://github.com/ORelio/Minecraft-Console-Client/issues/427 and also includes some minor improvements around when a specific config file could not be found (in particular reports the full path to the filename).
I have tested the changes via:
MinecraftClient.ini
```
[ScriptScheduler]
enabled=true
tasksfile=tasks.ini
```
tasks.ini:
```
[Task]
TriggerOnLogin=true
script=loginscript.txt
```
loginscript.txt
```
wait 10
send Hello From task
```

#427: Fix TriggerOnLogin doesn't work when /reco

---

MinecraftClient/ChatBot.cs
MinecraftClient/ConsoleIO.cs
MinecraftClient/Crypto/CryptoHandler.cs
MinecraftClient/McTcpClient.cs
MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/Protocol18Forge.cs
MinecraftClient/Protocol/IMinecraftCom.cs

This MR mainly adds an additional reporting when we encounter the `VarInt too big` issue. Note that there is also a `ReadNextVarIntRAW` where I haven't added the same since it does not seem to be the place where we encounter the exception.
Also fixed some Doc-Strings ;)

Add debugging to var int to big

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

See https://github.com/ORelio/Minecraft-Console-Client/issues/811#issuecomment-541873074.  Not tested at all.
The issue is that the client must always respond with a teleport confirm, even if it doesn't care about motion otherwise.  However, to get the teleport ID to confirm, all of the data before it needs to have been processed, or else it'll be reading the first field (the x position in this case, which is not a VarInt but still might happen to parse correctly as one) instead of the teleport ID.  The crash would happen if the x position has the first bit set in 5 bytes, which is uncommon (for one, it requires a negative coordinate, but then a bits need to be set too).  One such coordinate should be `-8577.5059` (`0xC0C0C0C0C154C986`), but again, I have not done any testing.

Fix VarInt too big for player position and look

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

issues #912
related:
#911 
#903 
Little explanation:
Player inventory is sent in `WindowItems` packet but didn't add the `window_actions[windowID] = 0;` when handling that packet.

Fix Console Client crashes when using the /inventory click command

---

.gitignore
MinecraftClient/ChatBot.cs
MinecraftClient/ConsoleIO.cs
MinecraftClient/Program.cs
MinecraftClient/Settings.cs

Adds a configuration setting in MinecraftClient.ini to strip all color codes and formatting from output when in BasicIO mode. Makes chat logs much more readable.
I use Docker to run Mono, so I need to use BasicIO mode to be able to run, stripping color and formatting codes makes it easier to interact with players.

Strip Minecraft Color Codes (§) in BasicIO mode

---

MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18Forge.cs
MinecraftClient/Protocol/Handlers/Protocol18Terrain.cs

First apologize for poor English and github manner.
I'm newbie at English and Github.
I had problem with using terrain and movements.
cpu usage going to 100%(in one thread) and timeout from server.
Some of Issues with 100% cpu usage are same reason.
The cause of problem is in packet processing.
List.RemoveAt(0); It will take time in proportion to n(=List.Count)
because RemoveAt(0) operation will reallocate size of n area and copying.
And packet processing will take time in proportion to m^2(m=packet size)
You can avoid this problem with using Queue instead List.
It can run packet processing in proportion to m(=packet size) time.
In 1.15 chunk packet size is around 15000.
so m^2 ≈ 225000000 it is so big.

Faster terrain packet handling in memory

---

MinecraftClient/Program.cs

Fixes #1116 
When in non-interactive mode (exitonfailure is enabled), returns distinct exit codes for some of the known failures.
This will let users handle them differently in their scripts.  For example I have a script that restart the console client if it's killed or crashes.  Right now I do something like this:
```
:start
MinecraftClient.exe
timeout /t 60
goto start
```
Now I can do this:
```
:start
MinecraftClient.exe
if '%ERRORLEVEL%'=='4' goto loginfailed
timeout /t 60
goto start
:loginfailed
echo 'Login failure. Stopping.'
pause
```
Doing this should avoid hammering the authentication servers with a bad password, and prevent getting IP blacklisted as easily.

Return exit codes for specific failures when in non-interactive mode

---

MinecraftClient/Settings.cs

this fixed the below issue
**User need to delete their old lang file first in order to auto-download the newest lang file**

Update translation file indexes web URL to the latest

---

MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs

Changed the "Terrain & Movements/Inventories/Entities are currently not handled for that MC version" message display upon startup from dark gray to red to more obviously point out the issue.

More transparent notifications about unsupported features

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/PacketType18Handler.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs

_Note: According to [Minecraft wiki](https://minecraft.gamepedia.com/Java_Edition_1.16.5), `1.16.4` and `1.16.5` share the same protocol number `754`._

Update to MC version 1.16.5

---

MinecraftClient/Protocol/Handlers/PacketPalettes/PacketTypePalette.cs
MinecraftClient/Protocol/Handlers/PacketType18Handler.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs

Fix #1419
_I am doubt about ignoring unknown packet ID is a good idea... since a bad/incorrect packet palette might also cause `IndexOutOfBound`_

Fix unknown packet ID cause crash

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/MicrosoftAuthentication.cs
MinecraftClient/Protocol/ProtocolHandler.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

Allow user to sign-in to their Microsoft Account by asking them to open sign-in page using browser. 
The downside is this require user to copy and paste lengthy content from and to console.
```
Sign-in page: 218 chars
Response URL: around 1500 chars
```
Also it is a bit lack of instruction because sign-in success will return a blank page. _Not a good method for people who don't read instructions._
---
At `ProtocolHandler.cs` L494:
`When you see a blank page after signing in, copy the link from browser and paste it below` 
My English is poor. I want user to copy and paste the URL back to MCC. @ORelio Could you please help me modify the sentence so that the instruction is more clear?

Implement browser sign-in method

---

MinecraftClient/Settings.cs

The fix is working. I manually changed all line break from `\r\n` to `\n` in `Resources\config\MinecraftClient.ini` for testing. With the fix, it is able to change all line break from `\n` to `\r\n` on Windows. I didn't test it on Linux/Mac but they should work as well.
Fix #1536

Adjust line break of default configuration file before writing

---

MinecraftClient/ExitCleanUp.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Program.cs
MinecraftClient/WinAPI/ExitCleanUp.cs

Tested with `ReplayMod` feature, which require proper quitting, on both Windows and Mono platform.
_Replay file created can be played properly, i.e. not corrupted_
Resolve #1559

Add ability to perform clean-up code before quitting

---

MinecraftClient/config/ChatBots/DiscordWebhook.cs

This is not a very smooth way of implementing the automatic start of the script with a URL. But as it was requested, I added it. I would rather prefere doing this with a script, which calls the bot and after that executes the "/dw changeurl" command.
A better way of implementation would be to add start parameters like "/script discordwebhook WebhookURL", which automatically starts the script with the URL. Unfortunately I could not find a way to read the arguments provided while calling the script.

Implement hardcoding the WebhookURL

---

MinecraftClient/McClient.cs

_I don't see any reason why it is there :P_
_And It slows down the shutdown speed_

Remove thread sleep in disconnect method

---

MinecraftClient/ChatBot.cs
MinecraftClient/McClient.cs

Taking command input as example, scheduling a task to run is better than creating a queue for everything that need to be run on the main thread.
#
My next plan is to create a method to schedule a delayed task for `ChatBot` API so that delaying a task will be easier.
https://github.com/ORelio/Minecraft-Console-Client/blob/0400ad89acf2aa3fad985ce45afbefda2d90db1d/MinecraftClient/ChatBots/AutoAttack.cs#L70-L73
https://github.com/ORelio/Minecraft-Console-Client/blob/0400ad89acf2aa3fad985ce45afbefda2d90db1d/MinecraftClient/ChatBots/AutoFishing.cs#L35-L42

Add method to schedule main thread task

---

MinecraftClient/ChatBots/RemoteControl.cs
MinecraftClient/McClient.cs

Sending illegal character will cause server to kick the client. This happens when using remote control to execute some command that contains color output.
Corresponding checking code in minecraft server source code:
```java
public static boolean isAllowedChatCharacter(char c0) {
return c0 != 167 && c0 >= ' ' && c0 != 127;
}
```
@ORelio If this looks good please merge it directly.

Remove illegal character in text message before sending

---

MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/Handlers/Protocol18Terrain.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs

This change allow low-end device to join server without being timeout. I decided not to change `/move` command as it doesn't cause connection timeout.
Tested with Raspberry Pi 4 4GB. It is possible to join server with `terrainandmovement` enabled now.
Resolve #1583

Use dedicated thread to process world data

---

MinecraftClient/DefaultConfigResource.resx

Cannot build with msbuild on ubuntu because it cannot find some resources that have invalid path names.

Invalid path name to resource causing build to fail

---

MinecraftClient/config/ChatBots/DiscordWebhook.cs

I suffered from some errors when I started the script. I soon found out, that the client detects some players leaving and I was wondering why, because there was not even a leaving message. I soon found out that the errors came from OnPlayerLeave() which returned a UUID but the name parameter was NULL. I don't know whether this is a bug in the client, but this should fix it for the script.

Prevent errors from OnPlayerLeave() returning NULL

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/PacketType18Handler.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs

There's no detail document available for 1.17.1 so I assumed no big change in the protocol.
https://minecraft.fandom.com/wiki/Java_Edition_1.17.1#General_2
Resolve #1669

Update to 1.17.1

---

MinecraftClient/Protocol/MojangAPI.cs

It seems like I have overseen something. In the Mojang API there is a way to request a players profile. Between several useless information, there is a Base64 encrypted JSON string, which reveals plenty information about the players skin and look. I implemented this feature, but I was a bit confused when it comes to a certain edge case:
There is a possibility, that a a player has no skin data. According to the [wiki](https://wiki.vg/Mojang_API) this happens when a Player has not set a custom skin. Seemingly this only applies until the first skin change of an account, since I was not able to recreate this, by changing my skin to Steve. If these cases occur, you can still evaluate their skin by checking their UUID, since even UUIDs have a Steve skin and odd ones an Alex skin.
I am not sure …

Addition to MojangAPI.cs

---

MinecraftClient/ChatBot.cs
MinecraftClient/ChatBots/ScriptScheduler.cs
MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftCom.cs

I just implemented what I requested in an Issue. Hope I did it right, because this is my first pull request. Feel free to change anything or tell me what should be different, if there is any kind of Enhancement or Problem to take care of. Basically this change allows MCC-Users to use `SpectatorTeleport(Player from GetEntities())` and `SpectatorTeleport(new Guid(String of Player or Entity-UUID))` int their Chatbots.

Spectator-Teleport Implementation

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

The Dimension field of `Respawn` packet have changed from Identifier to NBT Tag Compound in 1.16.2 and I forgot to update the packet at that time in PR #1214
Document for [1.16.1](https://wiki.vg/index.php?title=Pre-release_protocol&oldid=15895#Respawn) and [1.16.2](https://wiki.vg/index.php?title=Pre-release_protocol&oldid=16001#Respawn)
I am just wondering why the program didn't crash for like almost 2 years with the mistake there.

Fix respawn packet

---

MinecraftClient/Commands/SetRnd.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Resources/lang/de.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/config/README.md

Hello there! As #1830 requested a random delay feature for the script scheduler, I had an idea how to implement it.
Therefore I added the "setrnd" command. As the name suggests it is pretty similar to the already existing "set" command.
The only difference is the syntax, you use it as the following:
| Command | Effect |
|---|---|
|`setrnd varname -10to10` | This sets the variable to a value between -10 and 10.|
|`setrnd varname string1,string2,string3,string4...` | This sets the variable value to one of the strings. <br> You can use as many comma seperated strings as you want.|
Due to the fact, that we are using local variables here, it can be used in all kinds of scripts. An example:
```
send Hello server.
setrnd waittime 50to100
wait %waittime%
send Waited: %waittime%
setrnd name …
```

Add setrnd command

---

MinecraftClient/Commands/Move.cs
MinecraftClient/Commands/SetRnd.cs

If you enter only `/move` the client crashes, since there is no first element [here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Commands/Move.cs#L25).

Fix /move crash and /setrnd

---

MinecraftClient/Protocol/MicrosoftAuthentication.cs
MinecraftClient/Protocol/ProtocolHandler.cs

I found that making refresh token to work for both sign method is not as simple as saving the client ID. The whole request body is also different, making the implementation more complex. As a result, I disabled the refresh token for MCC sign in method for now.
Fix #1877

MSA: Disable refresh token for MCC signin method

---

MinecraftClient/MinecraftClient.csproj
MinecraftClient/Scripting/DynamicRun/Builder/Compiler.cs

Scripting was inadvertently broken when i turned on [Single File Application](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli) compilation.
I noticed a peculiar warning while trying to fix the automated builds, warning [IL3000](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/warnings/il3000), about assembly paths being empty on SFAs, originating from `Compiler.cs`. The `MinecraftClient.dll` file is now inaccessible since it is embedded into the executable.
The fix that I have done here is to simply extract the required assemblies from the executable into memory and load them accordingly.

Scripting Hotfix for .NET

---

.github/workflows/build-and-release.yml

To help reduce the amount of people requiring to build MCC for their ARM servers and devices (i.e. Raspberry Pis and ARM VPSes), we should start adding ARM releases as part of our precompiled builds.
Mentioning @milutinke as requested.

Add ARM64 as a precompiled binary release

---

MinecraftClient/Command.cs
MinecraftClient/Commands/Move.cs
MinecraftClient/Mapping/Location.cs
MinecraftClient/Mapping/Movement.cs
MinecraftClient/McClient.cs

resolve #724
Usage:
``/move 1 2 3``
``/move 1.23 4.56 7.89``
``/move ~5 ~1 ~-7``
``/move ~.2 ~.5 ~-.67``
``/move ~.2 63.5 ~-.67``

Support for using relative coordinates in /move

---

Docker/Dockerfile
Docker/start-latest.sh

Fixed and tested the Docker image.
I've updated the image to use the official Microsoft .NET image and I've updated the process to include an option for specific version downloading if someone would like to run a specific build instead the latest one.
I've tested it on Windows 10 and it's working for me.
How it looks like
https://streamable.com/01lia7
Can someone test it on Linux and macOS, so we can confirm that it's working on all platforms, before we merge?

Fixed the Docker image.

---

MinecraftClient/Commands/ExecIf.cs
MinecraftClient/Commands/ExecMulti.cs
MinecraftClient/McClient.cs
MinecraftClient/MinecraftClient.csproj
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

Added a way to execute multiple commands with a single command with:
```
/execmulti <command 1> -> <command 2> -> <command 3> -> ...
```
Another idea, we could implement a field in `PerformInternalCommand` which would indicate a failure of the execution, so we could make a `/chain` command which would stop if one of the commands has failed to execute, this could be useful in some scenarios, tho this would be a bit tricky to implement and to keep backwards compatibility.

Added a way to execute multiple commands with a single command

---

MinecraftClient/Mapping/MapIcon.cs
MinecraftClient/Mapping/MapIconType.cs
MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/DataTypes.cs
MinecraftClient/Protocol/Handlers/PacketType18Handler.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Scripting/ChatBot.cs

This will allow us to process map data and render maps into images with a chat bot, so people can solve those annoying captchas.
However, we need to figure out how the maps are being rendered,
Packet info: https://wiki.vg/Protocol#Map_Data
Map Data format: https://minecraft.fandom.com/wiki/Map_item_format (*NOTE: Colors on the wiki are outdated, we will have to look at the code*)
Minecraft Classes:
- Packet class: `net.minecraft.network.protocol.game.ClientboundMapItemDataPacket`
- Map Data class: `net.minecraft.world.level.saveddata.maps.MapItemSavedData`
Found some libraries for reference (a bit dated tho):
- https://github.com/LB--/MCModify/blob/java/src/main/java/com/lb_stuff/mcmodify/minecraft/Map.java
- https://github.com/spookymushroom/minecraftmap/blob/master/minecraftmap/__init__. …

Fully implemented Map Data packet + Fixed 1.14 not working.

---

MinecraftClient/ChatBots/AutoFishing.cs
MinecraftClient/ChatBots/BotsCommand.cs
MinecraftClient/ChatBots/PlayerListLogger.cs
MinecraftClient/ChatBots/Reload.cs
MinecraftClient/McClient.cs
MinecraftClient/Program.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Scripting/ChatBot.cs
MinecraftClient/Settings.cs

This is a new PR for #2167, the reason for a new PR is that I do not want to deal with all the merge conflicts, since the version of the code I've worked in is quite outdated.
`/reload` is now only hard reload, no more soft reload (It unloads all Chat Bots and loads them back in by default).
Other command are unchanged.
All Chat Bots are now back to their original state.
Tested everything except Mailer and it works, I assume that Mailer Will work too, I do not see a reason for it not to work.
The PR is ready for merge as far as I am considered, going to leave it a bit for potential feedback.

Reload Settings and Chat Bots, Fixed PlayerListLogger Chat Bot, added %datetime%

---

MinecraftClient/ChatBots/AntiAFK.cs
MinecraftClient/McClient.cs
MinecraftClient/Resources/config/MinecraftClient.ini
MinecraftClient/Resources/lang/en.ini
MinecraftClient/Settings.cs

Updated the Anti AFK Chat Bot to have an option of using the terrain handling and to use sneaking when using the old command method.
Note: The terrain handling option is disabled by default.
Now the chat bot can walk randomly in the given range, if it fails to get to a randomly generated location it will try 20 more times before using the old command method, in addition to sending a command now the bot also does toggle sneak.
Also, now the bot supports random intervals, example: `delay=30-200`
**NOTE:**
If you're using Terrain Handling feature, make sure to enclose the bot within an enclosure of some size to prevent it from wandering off randomly, the recommended size is 5x5x5.

Updated Anti AFK Bot to have Terrain Handling and random intervals option

---

MinecraftClient/ChatBots/Map.cs
MinecraftClient/Commands/Dig.cs
MinecraftClient/Commands/Leavebed.cs
MinecraftClient/Mapping/MaterialExtensions.cs
MinecraftClient/Resources/lang/en.ini

Added a new command for usage of the bed:
- Sleep in a bed: `/bed sleep <x> <y> <z>` (Supports relative coordinates, eg. `/dig 124 ~ ~-1`) (Shorter: `/bed s <x> <y> <z>`)
- Leave a bed: `/bed leave` (Shorter: `/bed l`)
Added relative coordinates support for the  `/dig` command.

Added a command for easier usage of the bed (/bed), Added relative coordinates support for the /dig command.

---

.github/workflows/build-and-release.yml

This adds a line to the build script that will not build commits with `README` on the title.
Additionally, add `[skip ci]` or `[ci skip]` for future commits that you don't want to build a binary with, for minor changes for example. `README` is still skipped, so it's not necessary to add them there.

Update build actions to skip documentation updates

---

MinecraftClient/Mapping/MaterialExtensions.cs
MinecraftClient/Mapping/Movement.cs

Implemented climbing up/down for:
- Vines
- Weeping Vines
- Twister Vines
- Ladders
NOTE:
There is a downside, when climbing down the bot will walk in air for last 2-3 blocks, haven't figured a way around + the code for `IsOnGround` had to be "hacked" for vines to work (haven't noticed any side effects but it's ugly).
Someone needs to improve upon this, tho we need to change the path finding code to be as in Botcraft, I've been staring at this code for too long.
Video demonstration:
https://streamable.com/uq33ak

Implemented climbing up/down

---

MinecraftClient/ChatBots/DiscordBridge.cs
MinecraftClient/ChatBots/Map.cs

Fixed Map Chat Bot not sending maps in case the Discord Bridge was not ready and connected.
Now images are queued up for sending until the Discord Bridge bot is ready and connected.

Fixed Map Chat Bot sending images to Discord when just connecting.

---

MinecraftClient/ChatBots/DiscordBridge.cs
MinecraftClient/Resources/lang/en.ini

Added try catch clauses and message timeout setting.
This should prevent crashing when the DiscordSharp cancels the task while sending a message.
Exceptions are reported in the Debug channel.

Another bug fix and added safeguards to the Discord Bridge chat bot.

---

MinecraftClient/Commands/Entitycmd.cs

Fixes #2345.
Now the command works as expected and when the type of interactions isn't passed and the second argument is an entity type we show a list of entities of that type.

Fixes the bug in entity command that doesn't allow passing entity types as second argument

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Seems like the fields are not swapped when testing in 1.19.3 vanilla/paper server
Fix #2429

SetExperience: Revert 1.19.3 fields swap

---

.github/workflows/build-and-release.yml

As reported in #2424.
This PR makes the following changes:
1. Actually makes the entire build fail when fetching translations fails, but continues building if it is skipped. This was broken in #2424.
The translation cache is actually a _crucial_ part of the system, as fetching the translations per build in parallel is _not allowed_ by the Crowdin API, and returns an error.
2. Fetching the translations also fetches the repository, so we skip checking out the repository if fetching the translations was successful.

Fix fetching translations for github actions

---

MinecraftClient/ChatBots/FollowPlayer.cs

Putting limit counter at the topmost will cause it to miss many target player movement event. In my case it receive zero and doesn't move at all.
We should first filter out target player movement event before applying the limit counter so that the bot always receive target player movement.

FollowPlayer: Improve player detection

---

MinecraftClient/Scripting/DynamicRun/Builder/Compiler.cs

- Fixes 2458
- Change error wording around scripting
- Prevent duplicating the binary for scripting

Scripting Hotfix for #2458

---

MinecraftClient/Commands/Entitycmd.cs
MinecraftClient/McClient.cs

Partially fixed interaction with Armor Stand
There is a problem, the bot is able to put equipment on, but it only can take back the helmet, I have tried using the `/look` command to change the yaw and pitch and to try to pick up a chest plate when the bot hand was empty and it would not work.
No idea why this is happening, needs further research and testing.
Also, the attack won't work, tried sending multiple packets at the same time to test it out, it does not work, no idea why.
So maybe someone else has an idea.
https://user-images.githubusercontent.com/441903/228941588-4da31af3-05ec-47c4-81a3-b26e81c701fc.mp4

Partially fixed interaction with Armor Stand

---

MinecraftClient/Protocol/Handlers/DataTypes.cs

Fixed crash on 1.8 when receiving entity data
The packet optional fields for Velocity were read all the time

Fixed crash on 1.8 when receiving entity data

---

MinecraftClient/Protocol/Handlers/Packet/s2c/DeclareCommands.cs

From #2473
The crash was casued by new undocumented parser type for `time`. It looks like an `int` and takes 4 bytes, causing command parser to read 4 bytes less and mess up the reading afterward.
This PR also fixes word "parse" being misspelled.

DeclareCommand: Fix 1.19.4 crash

---

MinecraftClient/ChatBots/Alerts.cs

Made Chatbot.Alert TriggerByWords case insensitive. until now if you placed any string that contains an **uppercase** in "Matches" or "Excludes" array, it wouldn't be detected in chat This was because chat text would go trough .ToLower() before comparing and Matches array didn't.

Made Alert.cs TriggerByWords method case insensitive

---

MinecraftClient/Protocol/Handlers/DataTypes.cs

The Entity object data field was being read but not set on the entity, thus the Auto Fish bot did not work properly because it was using the Object Data of the fishing bobber entity.
Reported as working by players.

Fixed Auto Fishing not working

---

Docker/start-latest.sh

Really useful during development/testing docker.
Simply pass MCC_SKIP_REDOWNLOAD

Docker: allow skip MinecraftClient download if MCC_SKIP_REDOWNLOAD defined

---

MinecraftClient/ConsoleIO.cs
MinecraftClient/Mapping/CommandBlockFlags.cs
MinecraftClient/Mapping/CommandBlockMode.cs
MinecraftClient/Mapping/Direction.cs
MinecraftClient/Mapping/Material2Tool.cs
MinecraftClient/McClient.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Scripting/ChatBot.cs

The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.

Update Minecraft wiki links to new domain

---

MinecraftClient/McClient.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/IMinecraftComHandler.cs
MinecraftClient/Scripting/ChatBot.cs

Fixed entity yaw and pitch not changing when an entity/player moves their head.

Fixed entity rotations

---

MinecraftClient/ChatBots/WebSocketBot.cs
MinecraftClient/Resources/ConfigComments/ConfigComments.Designer.cs
MinecraftClient/Resources/ConfigComments/ConfigComments.resx
MinecraftClient/Resources/Translations/Translations.Designer.cs

To allow for running the WebSocket Bot easily in containers I wanted a way to be able to have the bot do a DNS lookup of a given string, this PR adds the desired functionality.
I have tested it with a few cases, including that the default "127.0.0.1" works (NOTE: I'm using my Python bindings to test this which can be found at [mcc.py](https://github.com/Zorua162/mcc.py). 
However, with these changes "localhost" can now also be used as an option. The IP still gets resolved to "127.0.0.1", but its a nice quality of life thing.
I also tested the case of Non-sensical IPs such as "127.0.0.0.1", which resulted in the expected error, and IPs such as "aaa", which also resulted in the expected error.
This implementation **doesn't** allow dangerous wildcards as the hostname such as "*", however if …

Add an IP lookup to the WebSocketBot

---

MinecraftClient/ChatBots/WebSocketBot.cs

I noticed that I wasn't getting any reply when I changed my session name, upon looking at the code it turns out this response was getting sent to the old session name. I have added a line which creates a new responder object with the new id to fix this.

Websocket bot: Create new Responder object that will respond to the session's new name

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs
MinecraftClient/Protocol/Session/SessionToken.cs
MinecraftClient/Resources/ConfigComments/ConfigComments.Designer.cs
MinecraftClient/Resources/ConfigComments/ConfigComments.resx
MinecraftClient/Resources/Translations/Translations.Designer.cs
MinecraftClient/Resources/Translations/Translations.resx
MinecraftClient/Settings.cs

To use Yggdrasil, u need to change the following in MinecraftClient.ini.
```
AccountType = "yggdrasil"
AuthServer = { Host = "littleskin.cn", Port = 443 }
```
When facing a multi-player account, the `selectedProfile` is None and u need to input the player name to select.
- May meeting some errors when trying to join a [Velocity](https://papermc.io/software/velocity) Server.
- I'm poor in C#, some logics may be strange.
Some code comes from https://github.com/Hikari1nVoid/MCC-authlib ,but there are many errors in the original fork.

Add Yggdrasil Login

---

MinecraftClient/Protocol/Handlers/Protocol16.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs
MinecraftClient/Protocol/ProtocolHandler.cs
MinecraftClient/Protocol/Session/SessionToken.cs

Implementation of Yggdrasil login broke Microsoft login by not including it to the session check conditionals.
This PR fixes it.

Restore ability to login with Microsoft broken after Yggdrasil authentication implementation

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Fixed issues with chat packets
```
Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ChatMessage. (PacketID: 55, Protocol: 764, LoginPhase: False, InnerException: System.Collections.Generic.KeyNotFoundException).
---> System.Collections.Generic.KeyNotFoundException: The given key 'text' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
--- End of inner exception stack trace ---
at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
at …
```

Fixed chat issues

---

MinecraftClient/Protocol/Handlers/Protocol18.cs

Tested version:
- 1.20.1 Forge
Occasionally get OperationCanceledException when typing /reco or /quit
```
> Unhandled exception. System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Collections.Concurrent.BlockingCollection`1.Add(T item, CancellationToken cancellationToken)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.PacketReader(Object o)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at …
```

fix(Protocol18.cs): OperationCanceledException when /reco or /quit

---

MinecraftClient/Protocol/Handlers/DataTypes.cs

The issue was that Chat was being read as a string instead of as NBT structure in 1.20.4

Fixed a crash on Entity Metadata

---

MinecraftClient/ChatBots/AutoRelog.cs
MinecraftClient/McClient.cs
MinecraftClient/Program.cs

Closes #2691, hopefully, by having AutoRelog handle reconnecting when it is enabled.
When it is disabled, it reverts to the basic reconnection handler found in `McClient`.
Also fixes the following issues:
---
- Overriding the version when joining a server that does not broadcast it's protocol version (i.e. a Minecraft server with Query/Server List Ping disabled, or a server behind ViaVersion (always returns protocol version -1)).
It started ignoring the version that was typed in the console and started prioritizing the version in the config.
Commit c78245c fixes that by passing parameters to the restart functions being called, and utilizing variables that are supposed to be used for this reason, that was somehow no longer being used.
---
- Offline client reconnects by authenticating with …

Fix general issues with logging in/relogging

---

MinecraftClient/Protocol/Handlers/PacketType18Handler.cs

Fix #2704 
The commit [Implemented 1.20.3](https://github.com/MCCTeam/Minecraft-Console-Client/commit/790e0bfe551397db1ba166732dc71ce29b61b0af#diff-c2f8a08cdba767fd5daf7ad820e7823e93b966674a8d9be571d2e51a752b8cd9) edited `PacketType18Handler.cs`
```diff
- < Protocol18Handler.MC_1_20_2_Version => new PacketPalette1194(),
- _ => new PacketPalette1202()
+ <= Protocol18Handler.MC_1_19_4_Version => new PacketPalette1194(),
+ <= Protocol18Handler.MC_1_20_2_Version => new PacketPalette1202(),
+ _ => new PacketPalette1204()
```
crashes the MCC at Protocol 763 (Protocol18Handler.MC_1_20_Version, 1.20 and 1.20.1) which works fine with PacketPalette1194 instead of 1202.

Fix(PacketType18Handler.cs): 1.20 Packet Palette

---

Docker/Dockerfile
Docker/start-latest.sh

Currently the example Dockerfile only works with amd64 architecture machines. This PR retains that default behaviour, however provides the ability to specify the MCC_PLATFORM environment variable, which changes the URL that the MCC release zip is downloaded from and so can be used to change the architecture to the desired one.

Add the ability to be able to use different platforms with the Dockerfile

---

.github/workflows/build-and-release.yml
MinecraftClient/CommandHandler/CmdResult.cs
MinecraftClient/Scripting/CSharpRunner.cs

- Changes the scripting error message from line numbers to presenting the actual line itself
- Attempts to fix "NotRun" errors by modifying the CSharpException to expose the inner exception message. (the NotRun value is only used in code paths that use CSharpException, so it is modified here.)

[skip ci] Miscellaneous scripting QoL improvements and fixes

---

.github/workflows/build-and-release.yml

Replaces the tixfactory release-manager action with a different one found in the marketplace, as the current one is no longer working.
Also removes the transition versions (zip files), as they were originally only intended as a hotfix for the newly added automatic update system.
This helps remove some of the duplication in the configuration.

Update the Github Actions Automated Build

---

MinecraftClient/Program.cs
MinecraftClient/Protocol/Handlers/Protocol18.cs

- Fixes an issue where connecting to a server with a compression threshold of 0 causes the client to not be able to connect
- Fixes an issue where OnSpawnPlayer is not called on 1.20.2 onwards
- Makes Sentry error reporting more reliable (by trying to capture all exceptions)

Fix multiple issues

---

MinecraftClient/Protocol/Message/ChatParser.cs

Fix for the `System.Collections.Generic.KeyNotFoundException: The given key 'minecraft:chat_type' was not present in the dictionary.` issue that has been plaguing us for weeks on end.
Not really sure if this fix is correct, but it works on my machine ¯\\\_(ツ)\_/¯

Hotfix for 'minecraft:chat_type' not present in the dictionary

---

MinecraftClient/ChatBots/AutoDig.cs
MinecraftClient/ChatBots/Farmer.cs
MinecraftClient/ChatBots/WebSocketBot.cs
MinecraftClient/Commands/Dig.cs
MinecraftClient/Mapping/DirectionExtensions.cs
MinecraftClient/McClient.cs
MinecraftClient/Scripting/ChatBot.cs

Fix prevent AntiCheat Block Breaking (In Scripts)
